model_id: "google/gemma-3-270m-it"
dataset_path: "wikimedia/wikipedia"
dataset_name: "20231101.fr"
device: "cuda"
max_sequence_length: 8192
batch_size: 8
gradient_accumulation_steps: 16
learning_rate: 3.0e-4
weight_decay: 0.01
warmup_steps: 1
max_steps: 25
compile: true
amp_enabled: true
amp_dtype: "bfloat16"
log_interval: 10
save_interval: 1000
eval_interval: 200
num_workers: 8
prefetch_factor: 2
embedding_noise_std: 0.05
pin_memory: true
vocab_size: 50000
num_examples: 1000
packing_batch_size: 10000
seed: 42
