model_id: "google/gemma-3-270m-it"
dataset_path: "wikimedia/wikipedia"
dataset_name: "20231101.fr"
device: "cuda"
max_sequence_length: 512
batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 5.0e-5
weight_decay: 0.01
warmup_steps: 200
max_steps: 15000
compile: false
amp_enabled: true
amp_dtype: "float16"
log_interval: 20
save_interval: 2000
eval_interval: 500
num_workers: 1
prefetch_factor: 2
embedding_noise_std: 0.05
pin_memory: true
vocab_size: 25000
num_examples: "all"
packing_batch_size: 1000
dist_timeout_seconds: 7200
